### ISSUE TITLE
"copy generated kitti_dbinfos_train.pkl into the kitti data path"

### ISSUE THREAD

**Issue by charmeleonz** [azhuantou/HSSDA#1]
Hi, 

Congrats on your paper's acceptance to CVPR'23! According to the provided instructions "copy generated kitti_dbinfos_train.pkl and kitti_infos_train.pkl into the kitti data path", there doesn't seem to be any newly generated kitti_dbinfos_train.pkl file? The previously generated one has already been moved into folder origin_label. I wonder what's to be done here.

Thx.

**Comment by azhuantou** [comment]
Hi. Thanks for your interest.

We're sorry for the error in our previous expression. All you need to do is copy the generated "kitti_infos_train.pkl" file, and we'll update the Readme to correct the mistake.
