### ISSUE TITLE
On the amount of labelled vs unlabelled data

### ISSUE THREAD

**Issue by charmeleonz** [azhuantou/HSSDA#11]
Hi there, I'd like to confirm the amount of labelled and unlabelled data used for Waymo experiments. When you say you use 1% of Waymo's training dataset, do you mean you use 1% of them as labelled and the rest (99%) as unlabelled?

**Comment by azhuantou** [comment]
Hi, thanks for your attention on our work.
For the Waymo dataset, we sampled 1% of the 798 training sequences (around 1.4k frame). Please refer to the experiment section ( 4.1Datasets and Evaluation Metrics) in the original paper for more details.

**Comment by charmeleonz** [comment]
> Hi, thanks for your attention on our work. For the Waymo dataset, we sampled 1% of the 798 training sequences (around 1.4k frame). Please refer to the experiment section ( 4.1Datasets and Evaluation Metrics) in the original paper for more details.

Thanks for the info.

So you sampled 1% of the training set (~1.4k). And did you use these 1.4k as labelled data? And where do the unlabelled data you used come from? And how many are they?

I doubt if this is made clear in the paper.

Thx.

**Comment by azhuantou** [comment]
Sorry for the late reply.

We used 1% of the training set as labeled data, and the rest 99% of the training set as the unlabeled data.

**Comment by charmeleonz** [comment]
Thanks!
