### ISSUE TITLE
Question for hierarchical supervision

### ISSUE THREAD

**Issue by IamJiyong** [azhuantou/HSSDA#13]
![image](https://github.com/azhuantou/HSSDA/assets/107848149/a6957f4f-6b1f-4a3a-89b6-ffde3ac7eec4)
Hello! I have a simple question for the loss function of hierarchical supervision.
Is the soft-weighted loss applied to all losses, including those from the point head and corner loss from the ROI head(or other), in PV-RCNN?

**Comment by azhuantou** [comment]
Hi, sorry for the late reply. 
For the soft-weighted loss, we did not consider other factors such as point head and corner loss.
