### ISSUE TITLE
Labelled and unlabelled split in the training set of Waymo dataset

### ISSUE THREAD

**Issue by VERITAS12** [azhuantou/HSSDA#18]
We want to reproduce the results in your paper on the Waymo dataset, but we don’t know which are the 1% labelled data and the remaining unlabelled data. Can you provide us with the specific split situation in your experiments? 

Thank you for your response.

**Comment by azhuantou** [comment]
Thanks for your attention. The 1% labeled data for the Waymo dataset is [here].(https://github.com/azhuantou/HSSDA/files/12721204/label_idx.txt).

**Comment by azhuantou** [comment]
Thanks for your attention. The 1% labeled data for the Waymo dataset is [here](https://github.com/azhuantou/HSSDA/files/12721204/label_idx.txt).

**Comment by VERITAS12** [comment]
Thanks!

**Comment by lejk8104** [comment]
I also have some questions regarding the re-implementation process for the Waymo dataset that I'd like to ask. Upon closely examining your code, I've noticed a few modifications in the EMA function. I have two questions about this:

![Screenshot from 2023-11-10 13-49-41](https://github.com/azhuantou/HSSDA/assets/41908895/c84fdc77-77de-4fbd-8234-9d7652bc2371)

Is there a specific reason you have modified the EMA function? Is it related to performance improvements?
I consider change_global_step to be an important hyperparameter. Did you also set this value to 2000 for the Waymo Dataset?
