### ISSUE TITLE
关于训练设置

### ISSUE THREAD

**Issue by dof-pikes** [azhuantou/HSSDA#2]
请问你们这个实验是在几张卡上跑的？我看到你给的配置： batch size ==12\ LR ==0.01\ BATCH_SIZE_PER_GPU: 2 ，可以详细介绍下吗？
非常感谢！！

**Comment by azhuantou** [comment]
你好，感谢你对我们工作的关注！
我们的实验是在6张A100显卡上进行的，基于PV-RCNN网络的实验batch size设置为60。

**Comment by dof-pikes** [comment]
非常感谢您的解答！
所以在6 × A100上 BATCH_SIZE_PER_GPU == 10？
请问你们readme里面给的训练命令 --batch size 12 以及配置文件PV RCNN SSL.yaml中 BATCH_SIZE_PER_GPU == 2 是针对几张什么显卡上的设置？

**Comment by azhuantou** [comment]
您好，readme中训练命令的设置是为了验证代码环境在双卡3090服务器上是否能够成功运行而建立的。
而我们论文中的实验和您理解的一样，6张A100显卡（40GB），batch size为60，BATCH_SIZE_PER_GPU == 10

**Comment by dof-pikes** [comment]
谢谢~
我在双卡3090上batch size 12运行，在进入下一个epoch，显存会爆。
而我设置batch size 10 复现不出来论文的结果，Ped差10个点，Car比您给的结果高0.6个点，Cyc差1个点。

**Comment by azhuantou** [comment]
您好~
为了公平对比，本论文的实验根据3DIoUmatch的实验设置，在三个不同的data splits上进行实验，最后将平均值作为性能进行报告。您可以尝试一下进行剩下的两个实验。
