### ISSUE TITLE
ImageSets_3dioumatch/train_0.02_1.txt generation

### ISSUE THREAD

**Issue by wanghangege** [azhuantou/HSSDA#22]
Hi, thanks for your work, can you please tell me how to generate “”ImageSets_3dioumatch/train_0.02_1.txt“” with my own kitti format data?

**Comment by azhuantou** [comment]
Hi @wanghangege, you can refer to the [split.py](https://github.com/yezhen17/3DIoUMatch-PVRCNN/blob/main/data/kitti/ImageSets/split.py) in the [3dioumatch](https://github.com/yezhen17/3DIoUMatch-PVRCNN) for generating you mentationed txt file.

**Comment by azhuantou** [comment]
Hi @wanghangege, you can refer to the [split.py](https://github.com/yezhen17/3DIoUMatch-PVRCNN/blob/main/data/kitti/ImageSets/split.py) in the [3dioumatch](https://github.com/yezhen17/3DIoUMatch-PVRCNN) for generating your mentationed txt file.

**Comment by wanghangege** [comment]
Thank you very much for your answer. I referred to [https://github.com/azhuantou/HSSDA/blob/main/tools/split.py](url). There is no problem so far. Thank you for your reply.
