### ISSUE TITLE
Demo.py training instructions

### ISSUE THREAD

**Issue by xbxdghx** [azhuantou/HSSDA#24]
Hi,I wrote a command to run the demo.py according to Openpcdet's instruction, but it was an error, can you show me the instruction for your running demo.py？
Here is my instruction：
`
python demo.py --cfg_file cfgs/kitti_models/pv_rcnn_ssl.yaml \
    --ckpt /home/lbh/HSSDA/output/kitti_models/pv_rcnn_ssl/pv_rcnn_002_1/ckpt/checkpoint_epoch_80.pth\
    --data_path /home/lbh/HSSDA/data/kitti/training/velodyne/000034.bin\
`
And the error is:
 File "/home/lbh/HSSDA/pcdet/models/detectors/pv_rcnn_ssl.py", line 27, in __init__
    self.label_idx = np.loadtxt(model_cfg['LABELED_FRAME_IDX'])
KeyError: 'LABELED_FRAME_IDX'

**Comment by azhuantou** [comment]
Hi, @xbxdghx 
From this error, it seems that you may need to specify the value for the parameter "LABELED_FRAME_IDX."

**Comment by xbxdghx** [comment]
Hi,could you please provide visual process instructions?

**Comment by azhuantou** [comment]
Hi, I adopt the code of the [kitti_object_vis](https://github.com/kuixu/kitti_object_vis) for visualization, instead of the demo.py.
You may follow the instructions to achieve the visualization.

**Comment by xbxdghx** [comment]
Thank you very much for your guidance, it was very useful. But when I want to run the test.py to get result.pkl by running the following command：
`
python test.py --cfg_file cfgs/kitti_models/pv_rcnn.yaml \
--batch_size 8 \
--ckpt /home/lbh/HSSDA/output/kitti_models/pv_rcnn_ssl/pv_rcnn_002_1/ckpt/checkpoint_epoch_80.pth  
`
 the result I get is like this:
2023-12-18 21:04:34,583   INFO  Car AP@0.70, 0.70, 0.70:
bbox AP:0.0000, 0.0000, 0.0000
bev  AP:0.0000, 0.0000, 0.0000
3d   AP:0.0000, 0.0000, 0.0000
aos  AP:0.00, 0.00, 0.00
Car AP_R40@0.70, 0.70, 0.70:
bbox AP:0.0000, 0.0000, 0.0000
bev  AP:0.0000, 0.0000, 0.0000
3d   AP:0.0000, 0.0000, 0.0000
aos  AP:0.00, 0.00, 0.00
Car AP@0.70, 0.50, 0.50:
bbox AP:0.0000, 0.0000, 0.0000
bev  AP:0.0000, 0.0000, 0.0000
3d   AP:0.0000, 0.0000, 0.0000
aos  AP:0.00, 0.00, 0.00
Car AP_R40@0.70, 0.50, 0.50:
bbox AP:0.0000, 0.0000, 0.0000
bev  AP:0.0000, 0.0000, 0.0000
3d   AP:0.0000, 0.0000, 0.0000
aos  AP:0.00, 0.00, 0.00
Pedestrian AP@0.50, 0.50, 0.50:
bbox AP:0.0000, 0.0000, 0.0000
bev  AP:0.0000, 0.0000, 0.0000
3d   AP:0.0000, 0.0000, 0.0000
aos  AP:0.00, 0.00, 0.00
Pedestrian AP_R40@0.50, 0.50, 0.50:
bbox AP:0.0000, 0.0000, 0.0000
bev  AP:0.0000, 0.0000, 0.0000
3d   AP:0.0000, 0.0000, 0.0000
aos  AP:0.00, 0.00, 0.00
Pedestrian AP@0.50, 0.25, 0.25:
bbox AP:0.0000, 0.0000, 0.0000
bev  AP:0.0000, 0.0000, 0.0000
3d   AP:0.0000, 0.0000, 0.0000
aos  AP:0.00, 0.00, 0.00
Pedestrian AP_R40@0.50, 0.25, 0.25:
bbox AP:0.0000, 0.0000, 0.0000
bev  AP:0.0000, 0.0000, 0.0000
3d   AP:0.0000, 0.0000, 0.0000
aos  AP:0.00, 0.00, 0.00
Cyclist AP@0.50, 0.50, 0.50:
bbox AP:0.0000, 0.0000, 0.0000
bev  AP:0.0000, 0.0000, 0.0000
3d   AP:0.0000, 0.0000, 0.0000
aos  AP:0.00, 0.00, 0.00
Cyclist AP_R40@0.50, 0.50, 0.50:
bbox AP:0.0000, 0.0000, 0.0000
bev  AP:0.0000, 0.0000, 0.0000
3d   AP:0.0000, 0.0000, 0.0000
aos  AP:0.00, 0.00, 0.00
Cyclist AP@0.50, 0.25, 0.25:
bbox AP:0.0000, 0.0000, 0.0000
bev  AP:0.0000, 0.0000, 0.0000
3d   AP:0.0000, 0.0000, 0.0000
aos  AP:0.00, 0.00, 0.00
Cyclist AP_R40@0.50, 0.25, 0.25:
bbox AP:0.0000, 0.0000, 0.0000
bev  AP:0.0000, 0.0000, 0.0000
3d   AP:0.0000, 0.0000, 0.0000
aos  AP:0.00, 0.00, 0.00

But the results of my training phase were normal. I want to ask what is your command for test.py?

**Comment by xbxdghx** [comment]
In my thinking, I should use pv-rcnn.yaml as the configuration file and the pv_rcnn_ssl .pth as the weight file for reasoning, but the test.py command I wrote along my lines is 0 as above. I wonder if that's how you reasoned?
