### ISSUE TITLE
About the dual threshold update period

### ISSUE THREAD

**Issue by AGI-player** [azhuantou/HSSDA#4]
Hello, thanks for your great work.
I found some differences between the paper and code. In the paper, Sec 3.3: "As mentioned in Sec. 3.2, in each training epoch,
the confident scene Dc will be updated, so all three dual_thresholds will dynamically change during training". But in the code, the  dual_thresholds is updated according to the mine_interval setting and the pseudo labels is updated in each epoch, is my understanding right?

**Comment by azhuantou** [comment]
Hi, thanks for your interest.

You understand it correctly. Initially, we set the mine_interval to 1 in the experiments. However, we later found that using a larger mine_interval could achieve similar performance and greatly reduce training time.

**Comment by AGI-player** [comment]
> Hi, thanks for your interest.
> 
> You understand it correctly. Initially, we set the mine_interval to 1 in the experiments. However, we later found that using a larger mine_interval could achieve similar performance and greatly reduce training time.

ok, thanks.
