### ISSUE TITLE
Full dataset validation

### ISSUE THREAD

**Issue by vehxianfish** [azhuantou/HSSDA#7]
Hi, Do you test on the entire Kitti dataset to validate performance?

**Comment by azhuantou** [comment]
Hi, thanks for your interest!
Do you mean to validate the performance generated by 100% train data?
We did not conduct this experiment, but based on the experimental procedure, you should be able to conduct it easily. However, we recommend commenting out the pseudo-label mining module at this time.

**Comment by vehxianfish** [comment]
Thanks!
