### ISSUE TITLE
Train with multiple GPUs

### ISSUE THREAD

**Issue by AGI-player** [azhuantou/HSSDA#8]
As in your code, you set "if det_annos is not None and rank == 0 " to process the distributed training mode in train_utils_ssl.py, but this means you can get dual_threshold value only in rank 0. All the other ranks, the dual_threshold will always be None type.  So in pv_rcnn_ssl.py, you have to process the condition that dual is None for example in line 98. This is not reasonable, why?

**Comment by azhuantou** [comment]
Thanks for your waiting.
After obtaining the dual thresholds in the main thread, they are broadcasted to other threads, so that each thread obtains the same dual thresholds and there will be no situation where the dual thresholds of a certain thread are None. The purpose of rank==0 is to gather the results (det_annos and aug_det_annos) in the main thread when calculating the dual thresholds.

**Comment by AGI-player** [comment]
> Thanks for your waiting. After obtaining the dual thresholds in the main thread, they are broadcasted to other threads, so that each thread obtains the same dual thresholds and there will be no situation where the dual thresholds of a certain thread are None. The purpose of rank==0 is to gather the results (det_annos and aug_det_annos) in the main thread when calculating the dual thresholds.

Thanks for your reply.
I train the model as follows:
![1](https://user-images.githubusercontent.com/99712469/236368301-4e43a711-85e7-434c-966d-39168ee084f6.jpg)
and add the "print code" in train_utils_sst.py and  pv_rcnn_ssl.py:
![2](https://user-images.githubusercontent.com/99712469/236368966-04be9d77-6643-42c1-b795-9d366726d578.jpg)
![3](https://user-images.githubusercontent.com/99712469/236368978-e5b995b6-5080-4ce8-9cec-c4181f8b72d6.jpg)
the results as follows:
![4](https://user-images.githubusercontent.com/99712469/236369087-5e953635-aeb1-4cb7-a977-245f07cbb667.jpg)
![5](https://user-images.githubusercontent.com/99712469/236370641-df053033-99da-41f0-b8df-5db0d20da675.jpg)
does this mean the dual thresholds value in ranks == 1 always be None type ? maybe my understanding is wrong, you can try it

**Comment by azhuantou** [comment]
Sorry for the mistake, you are right. 
I will recheck the released code when I'm free.
The following simple operation may solve this problem.
![image](https://user-images.githubusercontent.com/33474693/236717340-2528b51b-6779-4d9b-adfd-814ccbbbdbaf.png)

**Comment by AGI-player** [comment]
> Sorry for the mistake, you are right. I will recheck the released code when I'm free. The following simple operation may solve this problem. ![image](https://user-images.githubusercontent.com/33474693/236717340-2528b51b-6779-4d9b-adfd-814ccbbbdbaf.png)

ok, thanks a lot, I'll try it.

**Comment by azhuantou** [comment]
Closed. Feel free to reopen it if you have any further questions or concerns.
