### ISSUE TITLE
Why did you set pv_rcnn.eval() for creating pseudo labels?

### ISSUE THREAD

**Issue by IamJiyong** [azhuantou/HSSDA#9]
Hi, I want to ask you why you set the mode of the teacher network to evaluation when generating pseudo labels.

https://github.com/azhuantou/HSSDA/blob/30822d0cd8992a3b460f9f190abe076bed11f338/pcdet/models/detectors/pv_rcnn_ssl.py#L62

On implementations of other SSL papers, including 3DIoUMatch, they set it to training mode.

So I'm wondering why you changed it to eval. Can you answer why?

Thank you.

**Comment by azhuantou** [comment]
Hi, thanks for your interests!
I follow the released code of [fixmatch](https://github.com/kekmodel/FixMatch-pytorch/blob/master/models/ema.py).
Maybe you can find the reason in the original paper.

**Comment by IamJiyong** [comment]
I understand. Thanks a lot!

**Comment by dof-pikes** [comment]
Why the setting of  self.pv_rcnn.eval() is important? @IamJiyong
